<?xml version="1.0" encoding="UTF-8"?>
<robot generated="20200527 17:29:05.503" generator="Robot 2.9 (Python 2.7.16 on darwin)">
<suite source="/Users/bond/Documents/Paylo/Test-APIs/Approve_merchant.robot" id="s1" name="Approve merchant">
<test id="s1-t1" name="TC01 : Get merchant ID and Approve merchant.">
<kw name="Get merchant registered ID and approve">
<arguments>
<arg>200</arg>
</arguments>
<msg timestamp="20200527 17:29:05.868" level="FAIL">No keyword with name 'Get merchant registered ID and approve' found.</msg>
<status status="FAIL" endtime="20200527 17:29:05.868" starttime="20200527 17:29:05.868"></status>
</kw>
<status status="FAIL" endtime="20200527 17:29:05.868" critical="yes" starttime="20200527 17:29:05.863">No keyword with name 'Get merchant registered ID and approve' found.</status>
</test>
<status status="FAIL" endtime="20200527 17:29:05.871" starttime="20200527 17:29:05.507"></status>
</suite>
<statistics>
<total>
<stat fail="1" pass="0">Critical Tests</stat>
<stat fail="1" pass="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="1" id="s1" name="Approve merchant" pass="0">Approve merchant</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200527 17:29:05.537" level="ERROR">Error in file '/Users/bond/Documents/Paylo/common.robot': Importing test library 'SeleniumLibrary' failed: ImportError: cannot import name PY3
Traceback (most recent call last):
  File "/Users/bond/Library/Python/2.7/lib/python/site-packages/SeleniumLibrary/__init__.py", line 26, in &lt;module&gt;
    from SeleniumLibrary.base import DynamicCore, LibraryComponent
  File "/Users/bond/Library/Python/2.7/lib/python/site-packages/SeleniumLibrary/base/__init__.py", line 17, in &lt;module&gt;
    from .context import ContextAware
  File "/Users/bond/Library/Python/2.7/lib/python/site-packages/SeleniumLibrary/base/context.py", line 17, in &lt;module&gt;
    from SeleniumLibrary.utils import escape_xpath_value
  File "/Users/bond/Library/Python/2.7/lib/python/site-packages/SeleniumLibrary/utils/__init__.py", line 20, in &lt;module&gt;
    from .types import is_falsy, is_noney, is_string, is_truthy, PY3, WINDOWS
  File "/Users/bond/Library/Python/2.7/lib/python/site-packages/SeleniumLibrary/utils/types.py", line 19, in &lt;module&gt;
    from robot.utils import PY3, is_truthy, is_falsy
PYTHONPATH:
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
  /Users/bond/Library/Python/2.7/lib/python/site-packages
  /Library/Python/2.7/site-packages
  /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
  /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
  /Library/Python/2.7/site-packages/pip-20.0.2-py2.7.egg</msg>
<msg timestamp="20200527 17:29:05.831" level="ERROR">Error in file '/Users/bond/Documents/Paylo/common.robot': Importing test library 'JSONLibrary' failed: ImportError: No module named JSONLibrary
Traceback (most recent call last):
  None
PYTHONPATH:
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
  /Users/bond/Library/Python/2.7/lib/python/site-packages
  /Library/Python/2.7/site-packages
  /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
  /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
  /Library/Python/2.7/site-packages/pip-20.0.2-py2.7.egg</msg>
<msg timestamp="20200527 17:29:05.842" level="ERROR">Error in file '/Users/bond/Documents/Paylo/common.robot': Resource file 'Resources/Api/Keywords/Keyword_api_manage_merchant.robot' does not exist.</msg>
</errors>
</robot>
